database:
  host: localhost # host of your database
  port: 5432 # default port for postgres
  database: hardcore # name of your database. A database server can contain multiple databases
  user: username
  password: passy
ghost:
  distance: 50
starting_currency: 3000
shop:
  revive: 1000
  items:
    dirt:
      material: DIRT
      amount: 64
      cost: 25
    fire_pot:
      material: POTION
      amount: 1
      cost: 300
      effectType: FIRE_RESISTANCE
      duration: 300
      amplifier: 1
