name: HardcorePlugin
version: '2.0.0-alpha'
main: club.somc.hardcorePlugin.HardcorePlugin
api-version: '1.21'
commands:
  shop:
    description: Purchase items and upgrades.
    usage: /<command>
  mark_evil:
    description: Will mark a player as evil.
    usage: /<command> player reason
    permission: hardcore.admin
  extra_life:
    description: Will give a player an extra life.
    usage: /<command> player reason
    permission: hardcore.admin
